@TripsTestApi_HostAddress = http://localhost:5271

POST {{TripsTestApi_HostAddress}}/simple_login
Content-Type: application/json
{
  "userName": "user_pepsi"
}

###

POST {{TripsTestApi_HostAddress}}/simple_login
Content-Type: application/json
{
  "userName": "user_cocacola"
}

###

POST {{TripsTestApi_HostAddress}}/simple_login
Content-Type: application/json
{
  "userName": "user_fanta"
}

###

GET {{TripsTestApi_HostAddress}}/trips
SessionId: a3e0608c-ba43-4ae3-b5fe-f4ac871300b7